//! Suffix array backend utilities.

use std::ops::Deref;

use anyhow::{anyhow, Error};
use libsais::SuffixArrayConstruction;
use serde::{Deserialize, Serialize};

use crate::types::Base;

/// A suffix array stored as `u64` suffix positions.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(transparent)]
pub struct SuffixArray(Vec<u64>);

impl SuffixArray {
    /// Consume and return inner Vec.
    pub fn into_inner(self) -> Vec<u64> {
        self.0
    }
}

impl Deref for SuffixArray {
    type Target = [u64];
    fn deref(&self) -> &[u64] {
        &self.0
    }
}

impl TryFrom<&[Base]> for SuffixArray {
    type Error = Error;

    fn try_from(bases: &[Base]) -> Result<Self, Self::Error> {
        // SAFETY: Base is #[repr(u8)] and its enum discriminants perfectly
        // match the required suffix array lexicographical sort order.
        let sort_bytes: &[u8] = unsafe {
            std::slice::from_raw_parts(bases.as_ptr().cast::<u8>(), bases.len())
        };

        // Build the suffix array. Use OpenMP if feature is enabled.
        #[cfg(feature = "openmp")]
        let sa_raw = SuffixArrayConstruction::for_text(sort_bytes)
            .in_owned_buffer()
            .multi_threaded(libsais::ThreadCount::openmp_default())
            .run()
            .map_err(|e| anyhow!("{e:?}"))?;

        #[cfg(not(feature = "openmp"))]
        let sa_raw = SuffixArrayConstruction::for_text(sort_bytes)
            .in_owned_buffer()
            .single_threaded()
            .run()
            .map_err(|e| anyhow!("{e:?}"))?;

        // Extract the SA vec
        let mut sa_vec: Vec<i64> = sa_raw.into_vec();

        // Verify no negative indices were generated by libsais before casting
        #[cfg(debug_assertions)]
        {
            sa_vec.par_iter().for_each(|&pos_i64| {
                debug_assert!(pos_i64 >= 0, "libsais returned negative suffix position");
            });
        }

        // SAFETY: i64 and u64 have identical memory layout (size and alignment).
        // We take ownership of the buffer, stop the old Vec from running its Drop logic,
        // and reconstruct a new Vec<u64> from the exact same memory region.
        // This eliminates an O(N) allocation, slashing peak memory usage by 50%.
        let positions: Vec<u64> = unsafe {
            let ptr = sa_vec.as_mut_ptr() as *mut u64;
            let len = sa_vec.len();
            let cap = sa_vec.capacity();
            std::mem::forget(sa_vec);
            Vec::from_raw_parts(ptr, len, cap)
        };

        Ok(Self(positions))
    }
}
