[package]
name = "risearch"
version = "3.0.0-alpha.1"
edition = "2024"

[features]
default = []
prof = []

[dependencies]
anyhow = "1.0"
bincode = "1.3.3"
clap = { version = "4.5.54", features = ["derive"] }
env_logger = { version = "0.11", features = ["color"] }
flate2 = { version = "1.1.8", default-features = false, features = ["zlib"] }
itoa = "1.0"
libsais = { version = "0.2", default-features = false }
log = { version = "0.4", features = ["release_max_level_info"] }
needletail = "0.6.3"
rayon = "1.11"
savefile = "0.20.2"
serde = { version = "1.0.228", features = ["derive"] }
smallvec = "1.15.1"
tikv-jemallocator = "0.6"
zmij = "0.1"
zstd = "0.13"

[dev-dependencies]
assert_cmd = "2.1.2"
criterion = { version = "0.5", features = ["html_reports"] }
predicates = "3.1.3"
tabled = "0.18"
tempfile = "3.24.0"
rstest = "0.24"


[profile.release]
debug = false
lto = "fat"
codegen-units = 1

[profile.profiling]
inherits = "release"
debug = true
lto = false
