//! Bundled DSM tables.
//! Generated by tools/dsm/pipeline.py

use super::DsmTable;
use crate::types::Energy;

mod s95_0;
mod s95_25;
mod s95_37;
mod s95_42;
mod s95_50;
mod slh04_0;
mod slh04_25;
mod slh04_37;
mod slh04_42;
mod slh04_50;
mod t04_0;
mod t04_25;
mod t04_37;
mod t04_42;
mod t04_50;

pub(crate) static TABLES: &[(&str, i32, Energy, &DsmTable)] = &[
    ("t04", 0, t04_0::INITIATION, &t04_0::TABLE),
    ("t04", 25, t04_25::INITIATION, &t04_25::TABLE),
    ("t04", 37, t04_37::INITIATION, &t04_37::TABLE),
    ("t04", 42, t04_42::INITIATION, &t04_42::TABLE),
    ("t04", 50, t04_50::INITIATION, &t04_50::TABLE),
    ("slh04", 0, slh04_0::INITIATION, &slh04_0::TABLE),
    ("slh04", 25, slh04_25::INITIATION, &slh04_25::TABLE),
    ("slh04", 37, slh04_37::INITIATION, &slh04_37::TABLE),
    ("slh04", 42, slh04_42::INITIATION, &slh04_42::TABLE),
    ("slh04", 50, slh04_50::INITIATION, &slh04_50::TABLE),
    ("s95", 0, s95_0::INITIATION, &s95_0::TABLE),
    ("s95", 25, s95_25::INITIATION, &s95_25::TABLE),
    ("s95", 37, s95_37::INITIATION, &s95_37::TABLE),
    ("s95", 42, s95_42::INITIATION, &s95_42::TABLE),
    ("s95", 50, s95_50::INITIATION, &s95_50::TABLE),
];
